# Generated by Django 5.2 on 2025-04-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_extensions', models.TextField(help_text='Перечисли допустимые расширения через пробел, например: mp4 mov webm')),
            ],
        ),
    ]
