# Generated by Django 5.2 on 2025-04-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='asmr/chunks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
